### ISSUE TITLE
VTS keymaster failed when generating RSA key

### ISSUE THREAD

**Issue by massonju** [linaro-swg/kmgk#22]
Hello,

I am opening this issue because I have some errors around RSA key generation when I run VTS keymaster.

I am using a mediatek board with Android 11 and my build contains OP-TEE (v3.12), tee-supplicant, kmgk, xtest ...
FYI I don't have any issue when I run `xtest -l 15`.

However when I run VTS keymaster, all the tests which generate an RSA key are failing.

Example with `PerInstance/NewKeyGenerationTest#Rsa/0_default`:
```
$ ./tools/vts-tradefed run commandAndExit vts --abi arm64-v8a --module VtsHalKeymasterV3_0TargetTest --test PerInstance/NewKeyGenerationTest#Rsa/0_default
...
01-29 13:45:51 I/ModuleListener: [1/1] VtsHalKeymasterV3_0TargetTest PerInstance/NewKeyGenerationTest#Rsa/0_default FAILURE: hardware/interfaces/keymaster/3.0/vts/functional/keymaster_hidl_hal_test.cpp:1105: Failure
Expected equality of these values:
ErrorCode::OK
Which is: OK
GenerateKey(AuthorizationSetBuilder() .RsaSigningKey(key_size, 3) .Digest(Digest::NONE) .Padding(PaddingMode::NONE) .Authorizations(UserAuths()), &key_blob, &key_characteristics)
Which is: 0xffff0006
01-29 13:45:52 I/SuiteResultReporter: 
============================================
================= Results ==================
=============== Consumed Time ==============
    arm64-v8a VtsHalKeymasterV3_0TargetTest: 488 ms
Total aggregated tests run time: 488 ms
============== Modules Preparation Times ==============
    arm64-v8a VtsHalKeymasterV3_0TargetTest => prep = 447 ms || clean = 38 ms
Total preparation time: 447 ms  ||  Total tear down time: 38 ms
=======================================================
=============== Summary ===============
Total Run time: 36s
1/1 modules completed
Total Tests       : 1
PASSED            : 0
FAILED            : 1
============== End of Results ==============
============================================
```

On UART I have the following logs:
```
D/TA:  TA_InvokeCommandEntryPoint:1470 KM_GENERATE_KEY
D/TA:  TA_generateKey:268 TA_generateKey 268
D/TA:  TA_deserialize_auth_set:190 TA_deserialize_auth_set 190
D/TA:  TA_deserialize_auth_set:214 indirect_data_size:0
D/TA:  TA_deserialize_auth_set:222 indirect_base:0x800dc040
D/TA:  TA_deserialize_auth_set:241 elem cnt:9
D/TA:  TA_deserialize_auth_set:251 elem serialized size:80
D/TA:  param_deserialize:111 param tag:0x10000002
D/TA:  param_deserialize:111 param tag:0x30000003
D/TA:  param_deserialize:111 param tag:0x500000c8
D/TA:  param_deserialize:111 param tag:0x20000001
D/TA:  param_deserialize:111 param tag:0x20000001
D/TA:  param_deserialize:111 param tag:0x20000005
D/TA:  param_deserialize:111 param tag:0x20000006
D/TA:  param_deserialize:111 param tag:0x300001f5
D/TA:  param_deserialize:111 param tag:0x600002bd
D/TA:  TA_add_origin:466 TA_add_origin 466
F/TC:? 0 trace_syscall:151 syscall #13 (syscall_get_time)
D/TA:  TA_add_creation_datetime:491 TA_add_creation_datetime 491
D/TA:  TA_add_os_version_patchlevel:521 TA_add_os_version_patchlevel 521
D/TA:  TA_parse_params:160 TA_parse_params 160
D/TA:  TA_parse_params:201 Unused parameter with TAG = 20000001
D/TA:  TA_parse_params:201 Unused parameter with TAG = 20000001
D/TA:  TA_parse_params:201 Unused parameter with TAG = 20000006
D/TA:  TA_parse_params:201 Unused parameter with TAG = 300001f5
D/TA:  TA_parse_params:201 Unused parameter with TAG = 600002bd
D/TA:  TA_parse_params:201 Unused parameter with TAG = 100002be
D/TA:  TA_parse_params:201 Unused parameter with TAG = 300002c1
D/TA:  TA_parse_params:201 Unused parameter with TAG = 300002c2
D/TA:  TA_generateKey:307 key_algorithm=1 key_rsa_public_exponent=3
D/TA:  TA_fill_characteristics:282 TA_fill_characteristics 282
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
D/TA:  TA_push_param:141 TA_push_param 141
F/TC:? 0 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:? 0 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:? 0 trace_syscall:151 syscall #27 (syscall_cryp_obj_alloc)
D/TA:  TA_generate_key:419 key_size = 1024, sizeof(attrs_in) = 8, attrs_in_count = 1
F/TC:? 0 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:? 0 trace_syscall:151 syscall #54 (syscall_obj_generate_key)
E/TA:  TA_generate_key:422 Failed to generate key via TEE_GenerateKey, res = ffff0006
F/TC:? 0 trace_syscall:151 syscall #24 (syscall_cryp_obj_get_info)
F/TC:? 0 trace_syscall:151 syscall #28 (syscall_cryp_obj_close)
E/TA:  TA_generateKey:331 Failed to generate key, res=ffff0006
D/TA:  TA_serialize_rsp_err:432 res: -65530
D/TA:  TA_free_params:25 TA_free_params 25
D/TA:  TA_free_params:25 TA_free_params 25
D/TA:  TA_free_params:25 TA_free_params 25
D/TC:? 0 tee_ta_invoke_command:825 Error: ffff0006 of 4
```

I looked how the RSA key is generated on other projects:

https://github.com/linaro-swg/optee_examples/blob/master/acipher/ta/acipher_ta.c#L39
```
res = TEE_GenerateKey(key, key_size, NULL, 0);
```

xtest 4007:
https://github.com/OP-TEE/optee_test
```
-> xtest_tee_test_4007_rsa(ADBG_Case_t *c)                                            host/xtest/regression_4000.c
--> keygen_noparams(c, &session, key_types, ARRAY_SIZE(key_types))                    host/xtest/regression_4000.c
---> generate_and_test_key(c, session, key_types[n].key_type, 1, key_size, NULL, 0)   host/xtest/regression_4000.c
     |-> params = NULL and param_count = 0

----> ta_crypt_cmd_generate_key(c, s, key, key_size, params, param_count)))           host/xtest/regression_4000.c
-----> TEEC_InvokeCommand(s, TA_CRYPT_CMD_GENERATE_KEY, &op, &ret_orig)               host/xtest/regression_4000.c
------> TA_InvokeCommandEntryPoint(...)                                               ta/crypt/ta_entry.c
-------> TEE_GenerateKey(o, params[0].value.b, attrs, attr_count)                     ta/crypt/cryp_taf.c
```

In both cases `attrs` is NULL and `attr_count` set to 0.

So I "naively" removed these lines in `kmgk` project:
``` diff
modified   keymaster/ta/generator.c
@@ -322,8 +322,6 @@ keymaster_error_t TA_generate_key(const keymaster_algorithm_t algorithm,
 	uint32_t b = 0;
 	uint32_t curve = UNDEFINED;
 	uint8_t buffer[KM_MAX_ATTR_SIZE] = { 0 };
-	uint8_t *buf_pe = NULL;
-	uint64_t be_pe = 0;
 	TEE_Attribute *attrs_in = NULL;
 	uint32_t attrs_in_count = 0;
 
@@ -363,27 +361,6 @@ keymaster_error_t TA_generate_key(const keymaster_algorithm_t algorithm,
 		attributes = attributes_rsa;
 		attr_count = KM_ATTR_COUNT_RSA;
 		type = TEE_TYPE_RSA_KEYPAIR;
-		attrs_in = TEE_Malloc(sizeof(TEE_Attribute),
-							TEE_MALLOC_FILL_ZERO);
-		if (!attrs_in) {
-			EMSG("Failed to allocate memory for attributes");
-			res = KM_ERROR_MEMORY_ALLOCATION_FAILED;
-			goto gk_out;
-		}
-		attrs_in_count = 1;
-		buf_pe = TEE_Malloc(sizeof(rsa_public_exponent),
-							TEE_MALLOC_FILL_ZERO);
-		if (!buf_pe) {
-			EMSG("Failed to allocate memory for public exponent");
-			res = KM_ERROR_MEMORY_ALLOCATION_FAILED;
-			goto gk_out;
-		}
-		be_pe = TEE_U64_TO_BIG_ENDIAN(rsa_public_exponent);
-		TEE_MemMove(buf_pe, &be_pe, sizeof(rsa_public_exponent));
-		TEE_InitRefAttribute(attrs_in,
-					TEE_ATTR_RSA_PUBLIC_EXPONENT,
-					(void *) buf_pe,
-					sizeof(rsa_public_exponent));
 		break;
 	case KM_ALGORITHM_EC:
 		attributes = attributes_ec;
```
In that way `attrs_in` is NULL and `attr_in_count` set to 0.

And now when I run `VtsHalKeymasterV3_0TargetTest` I don't have errors.

Do you have any thoughts on my issue ?
because I cannot explain why I need to do that ...

Thanks

**Comment by vchong** [comment]
@massonju Some tests in the KM3 test suite set the RSA public exponent to 3. With the introduction of https://github.com/OP-TEE/optee_os/commit/338b123ee66ca6694372564000226549c99806b1 (based on NIST SP800-56B), any exponent value less than 65537 will return `TEE_ERROR_BAD_PARAMETERS` (0xffff0006), as seen above.

One of the following below can be done.
1. Add your changes above. With that, the check is skipped because `TEE_ATTR_RSA_PUBLIC_EXPONENT` isn't defined, so there are no errors, but the key created isn't exactly what the test asked for. I suppose the test has no way of checking if the key was created properly since it's returned as an encrypted blob, else it should have failed as well.
2. Revert the `optee_os` patch, which is what we're currently doing now in our test build, but that means we won't be NIST SP800-56B compliant for now.
3. Patch all tests in the test suite with an exponent of 3 to 65537, but then we'll have to change AOSP code.
4. Upgrade to suppor a higher version of KM, but currently we've no such plan.

Per https://source.android.com/security/keystore/tags#rsa_public_exponent, trustlets (TAs) **may** support the value of 3, which means we don't necessarily have to support it, but if we don't, we'll fail some tests in the KM3 test suite. We're currently considering whether to file an issue @ https://issuetracker.google.com to request changing all tests using an exponent of 3 to 65537, but since these are relatively old code [1], they might not be inclined to make any changes.

[1] All exponents in the KM4 test suites have been changed from 3 to 65537 (https://android.googlesource.com/platform/hardware/interfaces/+/ee1ccd88ba). The KM41 test suite seems to be using some sort of wrapper of the KM4 test suite library. Beyond 4.1, the interface has changed from HIDL to AIDL, along with the renaming of keymaster to keymint. All keymint tests use 65537 as well, as can be seen in https://android.googlesource.com/platform/hardware/interfaces/+/master/security/keymint/aidl/vts/functional/KeyMintTest.cpp.

**Comment by massonju** [comment]
Thanks a lot for your detailed response.
I think I will take the option 2. as you do for your test build.

have a nice day :)

**Comment by massonju** [comment]
Hi @vchong 

I also wanted to ask you, I had to cherry-pick the following commits from `kmgk_pta_3.3.0` branch on `optee-os` project:
```
ab43191a * core: crypto: change supported HMAC key size ranges
962d0040 * libutee: remove restrictions for TEE_ALG_RSA_NOPAD
6dd386fc * core: crypto: detect elliptic curve size
199d0b73 * core: crypto: add support MD5 hashes in RSA sign/verify
0cd6a35b * libtomcrypt: rsa: oaep: Use SHA-1 by default for MGF1
```

Do you know if there is a plan to merge these commits in the master ?

Thanks

**Comment by vchong** [comment]
Hi @massonju,

> Do you know if there is a plan to merge these commits in the master ?

  Yes but for various reasons the plan has been delayed. Also, it's not so direct to just submit a PR as some of the patches introduces a different default behavior or an algorithm that's not supported by GlobalPlatform or considered less secure so we've to figure out a way about it for AOSP without causing side effects for other platforms. We'll post an update as soon as possible. Please also consider 'Watch'ing the `optee_os` repo so that you get notified on PR submissions.

**Comment by massonju** [comment]
Okay got it, I see the point.
Indeed I will watch `optee-os` project to see if there is some progress. on this subject.

Thanks :)
