### ISSUE TITLE
ImportKey Size

### ISSUE THREAD

**Issue by hyunsYang** [linaro-swg/kmgk#27]
Hello,
I am opening this issue because I have a question about keymaster's imporkey.

When I import 2048 bits RSA key, I got error as below.
"RSA import key size 2048 must be less than 1024"

Is there any reason to limit key size to less than 1024?

keymaster/ta/parameters.c,  217 line
if (*key_algorithm == KM_ALGORITHM_RSA && *key_size != UNDEFINED
			&& ***key_size > 1024** && import) {
		EMSG("RSA import key size %d must be less than 1024", *key_size);
		return KM_ERROR_IMPORT_PARAMETER_MISMATCH;
	}

**Comment by vchong** [comment]
@hyunsYang This was in the original reference implementation that we received and I couldn't find any references wrt to this limitation either. Supported values should be 1024, 2048, 3072 and 4096 as per the `generateKey()` API. What happens if you remove the `*key_size > 1024` check? If there are no issues please put in a PR for the removal.
